version: '3.7'
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./api/.env
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'

  hapi-fhir-postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hapi
      POSTGRES_PASSWORD: hapi123
    volumes:
      - 'hapi-fhir-postgres:/var/lib/postgresql/data'

  mhis-api:
    build: ./api
    container_name: mhis_api
    restart: always
    depends_on:
      - postgres
    ports:
      - '8081:8080'
      - '5555:5555'
    env_file:
      - ./api/.env
    links:
      - postgres

  # mhis-ui:
  #   build: ./ui
  #   restart:  always
  #   depends_on:
  #     - mhis-api
  #   ports:
  #     - '8082:80'
  #   links:
  #     - mhis-api

  dhis2-db:
    image: mdillon/postgis:10-alpine
    command: postgres -c max_locks_per_transaction=100
    environment:
      POSTGRES_USER: dhis
      POSTGRES_DB: dhis2
      POSTGRES_PASSWORD: dhis

  dhis2-web:
    image: dhis2/core:2.33.0
    volumes:
      - ./dhis.conf:/DHIS2_home/dhis.conf
    ports:
      - '8085:8080'
    depends_on:
      - dhis2-db

  hapi-fhir-jpa:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-jpa
    restart: on-failure
    ports:
      - '8080:8080'
    volumes:
      - './hapi:/hapi'
    environment:
      SPRING_CONFIG_LOCATION: /hapi/application.yaml

  cloud-messaging:
    build:
      context: cloud-messaging
      dockerfile: Dockerfile
    container_name: cloud-messaging
    restart: always
    ports:
      - '8000:8000'
    # env_file: ./cloud-messaging/.env

volumes:
  db:
  hapi-fhir-postgres:
  hapi:
    external: true
