version: "3.7"
services:
  postgres:
    image: postgres:14-1-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
    # remove this in prod
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  nndak-api:
    build: .
    restart: always
    depends_on:
      - postgres
    ports:
      - '80:8080'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
      - DATABASE=nndak
  
volumes:
  db:
    driver: local