version: '3.7'
services:

  postgres:
    image: postgres:14-alpine
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - 'db:/var/lib/postgresql/data'

  hapi-fhir-postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: hapi
      POSTGRES_PASSWORD: hapi123
    volumes:
      - 'hapi-fhir-postgres:/var/lib/postgresql/data'

  mhis-api:
    build: ./api
    container_name: mhis-api
    restart: always
    depends_on:
      - postgres
    ports:
      - '8081:8080'
    env_file:
      - ./api/.env
    links:
      - postgres

  mhis-web:
    build: ./ui
    restart:  always
    depends_on:
      - mhis-api
    ports:
      - '8082:80'
    links:
      - mhis-api

  hapi-fhir-jpa:
    image: hapiproject/hapi:latest
    container_name: hapi-fhir-jpa
    restart: on-failure
    ports:
      - "8080:8080"
    volumes:
      - "./hapi:/hapi"
    environment:
      SPRING_CONFIG_LOCATION: /hapi/application.yaml

  cloud-messaging:
    build:
      context: cloud-messaging
      dockerfile: Dockerfile
    container_name: cloud-messaging
    restart: always
    # env_file: ./cloud-messaging/.env


volumes:
  db:
  hapi-fhir-postgres:
  hapi:
